catalogue/urls.py
"""reservations.catalogue URL Configuration
"""
from django.urls import path

from . import views

app_name='catalogue'

urlpatterns = [
    path('artist/', views.artist.index, name='artist-index'),
    path('artist/<int:artist_id>', views.artist.show, name='artist-show'),
    path('artist/edit/<int:artist_id>', views.artist.edit, name='artist-edit'),
    path('artist/update/<int:artist_id>', views.artist.update, name='artist-update'),
]

reservations/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('catalogue/', include('catalogue.urls')),
    path('admin/', admin.site.urls),
]

catalogue/models.py
from django.db import models

# Create your models here.

catalogue/models/artist.py
from django.db import models

class Artist(models.Model):
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)

    def __str__(self):
        return self.firstname +" "+ self.lastname

    class Meta:
        db_table = "artists"
        

catalogue/forms/ArtistForm.py
from django import forms
from  catalogue.models import Artist

class ArtistForm(forms.ModelForm):

    class Meta:
        model = Artist
        fields = '__all__'
        #exclude = ['mobile']  #mobile field is excluded

catalogue/views.py
from django.shortcuts import render

# Create your views here.

catalogue/views/artist.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponseRedirect

from catalogue.models import Artist
from catalogue.forms.ArtistForm import *

# Create your views here.
def index(request):
    artists = Artist.objects.all()
    
    return render(request, 'artist/index.html', {
        'artists':artists,
    })

def show(request, artist_id):
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant');

    title = 'Fiche d\'un artiste'

    return render(request, 'artist/show.html', {
        'artist':artist,
    })

def edit(request, artist_id):
    # Récupérer l'artiste à modifier
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant');
        
    form = ArtistForm(instance=artist)
    
    return render(request, 'artist/edit.html', {
        'form':form,
        'artist':artist,
    })

def update(request, artist_id):
    method = request.POST.get('_method', '').upper()

    # Vérifier s'il s'agit bien d'une méthode PUT
    if method == 'PUT':
        # Récupérer l'artiste à modifier
        try:
            artist = Artist.objects.get(id=artist_id)
        except Artist.DoesNotExist:
            raise Http404('Artist inexistant');

        # Créer un formulaire pour modifier un artiste existant, mais
        # utiliser les données du POST pour remplir le formulaire
        form = ArtistForm(request.POST, instance=artist)

        # Vérifier si les données du formulaire sont valides
        if form.is_valid():
            # Persister les données en base de données           
            form.save();

            return render(request, 'artist/show.html', {
                'artist':artist,
            })

    return HttpResponseRedirect('artist-show')

catalogue/templates/artist/edit.html
{% extends 'layouts/base.html' %}

{% block title %}Modifier un artiste{% endblock %}

{% block content %}
    <h2>Modifier un artiste</h2>

    <form action="{% url 'catalogue:artist-update' artist.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="_method" value="PUT">

        {{ form }}

        <button>Modifier</button>
        <a href="{% url 'catalogue:artist-show' artist.id %}">Annuler</a>
    </form>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à l'index</a></nav>
{% endblock %}

catalogue/templates/artist/index.html
{% extends 'layouts/base.html' %}

{% block title %}Liste des artistes{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <table>
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.firstname }}</td>
                <td><a href="{% url 'catalogue:artist-show' artist.id %}">{{ artist.lastname }}</a></td>
            </tr>
        {% empty %}
	    <tr>
	         <td colspan="2">Sorry, no artist in the database.</td>
	    </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

catalogue/templates/artist/show.html
{% extends 'layouts/base.html' %}

{% block title %}Fiche d'un artiste{% endblock %}

{% block content %}
    <h1>{{ artist.firstname }} {{ artist.lastname }}</h1>

    <div><a href="{% url 'catalogue:artist-edit' artist.id %}">Modifier</a></div>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à l'index</a></nav>
{% endblock %}

catalogue/templates/layouts/base.html
<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<title>Projet réservations - {% block title %}Bienvenue{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>